/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.PlanTreninga;
import domen.Sprava;
import domen.StavkaPlanaTreninga;
import domen.TrenutniPlanTreninga;
import domen.Vezbac;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.KlijentskiZahtev;
import komunikacija.ServerskiOdgovor;
import modeli.ModelTabeleStavke;

/**
 *
 * @author jovan
 */
public class PravljenjePlanaTreninga extends javax.swing.JFrame {
    Vezbac vezbac;
    /**
     * Creates new form PravljenjePlanaTreninga
     */
    public PravljenjePlanaTreninga() {
        initComponents();
        setTitle("Pravljenej plana treninga");
        setLocationRelativeTo(null);
        txtImePrezime.setEditable(false);
        tblStavka.setModel(new ModelTabeleStavke());
        popuniSprave();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavka = new javax.swing.JTable();
        cmbSprave = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBrojSerija = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrojPonavljanja = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDuzinaOdmora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtOpisVezbe = new javax.swing.JTextField();
        btnDodajPlan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnKreirajTrening = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNazivTreninga = new javax.swing.JTextField();
        txtSvrha = new javax.swing.JTextField();
        txtDuzinaTrajanja = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime i prezime vezbaca:");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        tblStavka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavka);

        cmbSprave.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Sprave:");

        jLabel4.setText("Broj serija:");

        txtBrojSerija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojSerijaActionPerformed(evt);
            }
        });

        jLabel5.setText("Broj ponavljanja:");

        jLabel6.setText("Duzina odmora (min):");

        jLabel8.setText("Opis vezbe:");

        btnDodajPlan.setText("Dodaj u plan treninga");
        btnDodajPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPlanActionPerformed(evt);
            }
        });

        jButton1.setText("Obrisi iz plana treninga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnKreirajTrening.setText("Kreiraj plan treninga");
        btnKreirajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajTreningActionPerformed(evt);
            }
        });

        jLabel9.setText("Naziv treninga:");

        jLabel10.setText("Svrha treninga");

        jLabel11.setText("Duzina trajanja (min):");

        jLabel12.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSprave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(605, 605, 605))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(42, 42, 42)
                                                .addComponent(txtDuzinaOdmora, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(txtBrojSerija, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(235, 235, 235))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOpisVezbe, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBrojPonavljanja, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSvrha, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(txtNazivTreninga)
                                    .addComponent(txtStatus))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btnKreirajTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOtkazi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDuzinaTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnDodajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbSprave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtBrojSerija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBrojPonavljanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtDuzinaOdmora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtOpisVezbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodajPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOtkazi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNazivTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtDuzinaTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSvrha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 37, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreirajTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDodajPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPlanActionPerformed
        
        try {
            if(txtBrojSerija.getText().isEmpty() || txtBrojPonavljanja.getText().isEmpty() || txtDuzinaOdmora.getText().isEmpty()
                || txtOpisVezbe.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
            }
            String brojSerija = txtBrojSerija.getText();
            String brojPonavljanja = txtBrojPonavljanja.getText();
            String duzinaOdmora = txtDuzinaOdmora.getText();
            String opisVezbe = txtOpisVezbe.getText(); 
            
            int brojPonavljanja1 = Integer.parseInt(brojPonavljanja);
            int brojSerija1 = Integer.parseInt(brojSerija);
            int duzinaOdmora1 = Integer.parseInt(duzinaOdmora);
            
            Sprava sprava = (Sprava) cmbSprave.getSelectedItem();
        
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavka.getModel();
        
            if(mts.vecPostoji(sprava)){
                JOptionPane.showMessageDialog(this,"Ova stavka vec postoji u tabeli");
                return;
            }
        
            StavkaPlanaTreninga spt = new StavkaPlanaTreninga(new PlanTreninga(), -1, brojSerija1,
                brojPonavljanja1, duzinaOdmora1, opisVezbe, sprava);
            
            mts.dodajStavku(spt);
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Niste uneli ispravne podatke, proverite da li ste u pollja broj serija,"
                    + " broj ponavljanja i duzina odmora uneli broj!");
        }   
    }//GEN-LAST:event_btnDodajPlanActionPerformed

    private void txtBrojSerijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojSerijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojSerijaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblStavka.getSelectedRow();
        
        if(selectedRow == -1 ){
            JOptionPane.showMessageDialog(this, "Molimo Vas izaberite stavku");
            return;
        }
        
        ModelTabeleStavke mts = (ModelTabeleStavke) tblStavka.getModel();
        mts.obrisiRed(selectedRow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKreirajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajTreningActionPerformed
        try {
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavka.getModel();
            if(mts.getLista().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti bar jednu stavku plana treninga");
                return;
            }
            if(txtNazivTreninga.getText().isEmpty() || txtSvrha.getText().isEmpty() || txtDuzinaTrajanja.getText().isEmpty() 
                    || txtStatus.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Sva polja ispod tabele su obavezna da bi kreirali plan treninga");
                return;
            }
            String nazivTreninga = txtNazivTreninga.getText();
            String svrhaTreninga = txtSvrha.getText();
            String duzinaTrajanja = txtDuzinaTrajanja.getText();
            String status = txtStatus.getText();
            
            int duzinaTrajanja1 = Integer.parseInt(duzinaTrajanja);
            TrenutniPlanTreninga trenutni = new TrenutniPlanTreninga(null, null, status);
            
            PlanTreninga planTreninga = new PlanTreninga(0, nazivTreninga, svrhaTreninga,
                    duzinaTrajanja1,mts.getLista(),vezbac,trenutni);
            
            
            KlijentskiZahtev kz = new KlijentskiZahtev(operacije.Operacije.KREIRANJE_PLANA_TRENINGA, planTreninga);
            komunikacija.KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = komunikacija.KomunikacijaSaServerom.getInstanca().primiOdgovor();
            
            
            if(so.isUspesno()){
                JOptionPane.showMessageDialog(this, so.getPoruka());
            }else{
                JOptionPane.showMessageDialog(this, so.getPoruka(),"GRESKA!",JOptionPane.ERROR_MESSAGE);
            }
            
            this.dispose();
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Niste uneli ispravne podatke, polje duzina trajanja mora btit broj");
        }       
        
    }//GEN-LAST:event_btnKreirajTreningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PravljenjePlanaTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PravljenjePlanaTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PravljenjePlanaTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PravljenjePlanaTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PravljenjePlanaTreninga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPlan;
    private javax.swing.JButton btnKreirajTrening;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbSprave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavka;
    private javax.swing.JTextField txtBrojPonavljanja;
    private javax.swing.JTextField txtBrojSerija;
    private javax.swing.JTextField txtDuzinaOdmora;
    private javax.swing.JTextField txtDuzinaTrajanja;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtNazivTreninga;
    private javax.swing.JTextField txtOpisVezbe;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSvrha;
    // End of variables declaration//GEN-END:variables

    void setVezbac(Vezbac v) {
        this.vezbac = v;
        txtImePrezime.setText(v.getIme()+" "+v.getPrezime());
    }

    private void popuniSprave() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(operacije.Operacije.VRATI_LISTU_SPRAVA);
        kz.setParametar(new Sprava());
        komunikacija.KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
        ServerskiOdgovor so = komunikacija.KomunikacijaSaServerom.getInstanca().primiOdgovor();
        
        ArrayList<Sprava> sprave = (ArrayList<Sprava>) so.getOdgovor();
        cmbSprave.removeAllItems();
        for (Sprava sprava : sprave) {
            cmbSprave.addItem(sprava);
            
        }
    }
}
